### ISSUE TITLE
konsol uyarıları

### ISSUE THREAD

**Issue by Ferhat-kus** [creators-team/Blank#33]
Componentler tasarlanırken lütfen uyarıları düzelttikten sonra merge edelim.
![resim](https://github.com/user-attachments/assets/e7924e70-fec8-4984-b5fb-8a47ef09d08c)

**Comment by 0fatihyildiz** [comment]
ordaki warm loglar provide edilmeyen inject fonksiyonlarindan geliyor loglari nasil absorbe edicegime henuz bakmadim eger ki absorbe edilmiyorsa boyle devam edebilir ya da composable a gecebiliriz
